version: "3"

includes:
  backend:
    taskfile: ./backend/Taskfile.yml
    dir: ./backend
  frontend:
    taskfile: ./frontend/Taskfile.yml
    dir: ./frontend
  infrastructure:
    taskfile: ./infrastructure/Taskfile.yml
    dir: ./infrastructure

tasks:
  setup:
    desc: Install project dependencies
    cmds:
      - task: frontend:install

  setup:test:
    desc: Install project dependencies and test browsers
    cmds:
      - task: frontend:install
      - task: frontend:browsers

  dev:
    desc: Start local infrastructure and run development servers
    cmds:
      - task: infrastructure:up
      - task: backend:migrate
      - task: dev:servers

  dev:servers:
    internal: true
    deps:
      - backend:dev
      - frontend:dev

  check:
    desc: Run all checks that do not require external services
    deps:
      - backend:check
      - frontend:check
