version: "3"

tasks:
  install:
    cmds:
      - bun install --frozen-lockfile

  dev:
    cmds:
      - bun run dev

  build:
    cmds:
      - bun run build

  test:
    cmds:
      - bun run test

  lint:
    cmds:
      - bun run lint

  typecheck:
    cmds:
      - bun run typecheck

  format:
    cmds:
      - bun run format

  check:
    cmds:
      - bun run check
